//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test15
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// City.
    /// </summary>
    // *** Start programmer edit section *** (city CustomAttributes)

    // *** End programmer edit section *** (city CustomAttributes)
    [ClassStorage("City")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("cityE", new string[] {
            "Город as \'Город\'",
            "ПлощадьГ as \'Площадь Г\'"})]
    [View("cityL", new string[] {
            "Город as \'Город\'",
            "ПлощадьГ as \'Площадь Г\'"})]
    public class city : ICSSoft.STORMNET.DataObject
    {
        
        private string fГород;
        
        private int fПлощадьГ;
        
        // *** Start programmer edit section *** (city CustomMembers)

        // *** End programmer edit section *** (city CustomMembers)

        
        /// <summary>
        /// Город.
        /// </summary>
        // *** Start programmer edit section *** (city.Город CustomAttributes)

        // *** End programmer edit section *** (city.Город CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Город
        {
            get
            {
                // *** Start programmer edit section *** (city.Город Get start)

                // *** End programmer edit section *** (city.Город Get start)
                string result = this.fГород;
                // *** Start programmer edit section *** (city.Город Get end)

                // *** End programmer edit section *** (city.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (city.Город Set start)

                // *** End programmer edit section *** (city.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (city.Город Set end)

                // *** End programmer edit section *** (city.Город Set end)
            }
        }
        
        /// <summary>
        /// ПлощадьГ.
        /// </summary>
        // *** Start programmer edit section *** (city.ПлощадьГ CustomAttributes)

        // *** End programmer edit section *** (city.ПлощадьГ CustomAttributes)
        [NotNull()]
        public virtual int ПлощадьГ
        {
            get
            {
                // *** Start programmer edit section *** (city.ПлощадьГ Get start)

                // *** End programmer edit section *** (city.ПлощадьГ Get start)
                int result = this.fПлощадьГ;
                // *** Start programmer edit section *** (city.ПлощадьГ Get end)

                // *** End programmer edit section *** (city.ПлощадьГ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (city.ПлощадьГ Set start)

                // *** End programmer edit section *** (city.ПлощадьГ Set start)
                this.fПлощадьГ = value;
                // *** Start programmer edit section *** (city.ПлощадьГ Set end)

                // *** End programmer edit section *** (city.ПлощадьГ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "cityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View cityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("cityE", typeof(IIS.Test15.city));
                }
            }
            
            /// <summary>
            /// "cityL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View cityL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("cityL", typeof(IIS.Test15.city));
                }
            }
        }
    }
}
