//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test15
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Street.
    /// </summary>
    // *** Start programmer edit section *** (street CustomAttributes)

    // *** End programmer edit section *** (street CustomAttributes)
    [ClassStorage("City")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("streetE", new string[] {
            "имя as \'Имя\'",
            "city as \'City\'",
            "city.Город as \'Город\'"}, Hidden=new string[] {
            "city.Город"})]
    [MasterViewDefineAttribute("streetE", "city", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Город")]
    [View("streetL", new string[] {
            "имя as \'Имя\'",
            "city.Город as \'Город\'"})]
    public class street : ICSSoft.STORMNET.DataObject
    {
        
        private string fимя;
        
        private IIS.Test15.city fcity;
        
        // *** Start programmer edit section *** (street CustomMembers)

        // *** End programmer edit section *** (street CustomMembers)

        
        /// <summary>
        /// имя.
        /// </summary>
        // *** Start programmer edit section *** (street.имя CustomAttributes)

        // *** End programmer edit section *** (street.имя CustomAttributes)
        [StrLen(255)]
        public virtual string имя
        {
            get
            {
                // *** Start programmer edit section *** (street.имя Get start)

                // *** End programmer edit section *** (street.имя Get start)
                string result = this.fимя;
                // *** Start programmer edit section *** (street.имя Get end)

                // *** End programmer edit section *** (street.имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (street.имя Set start)

                // *** End programmer edit section *** (street.имя Set start)
                this.fимя = value;
                // *** Start programmer edit section *** (street.имя Set end)

                // *** End programmer edit section *** (street.имя Set end)
            }
        }
        
        /// <summary>
        /// Street.
        /// </summary>
        // *** Start programmer edit section *** (street.city CustomAttributes)

        // *** End programmer edit section *** (street.city CustomAttributes)
        [PropertyStorage(new string[] {
                "city"})]
        [NotNull()]
        public virtual IIS.Test15.city city
        {
            get
            {
                // *** Start programmer edit section *** (street.city Get start)

                // *** End programmer edit section *** (street.city Get start)
                IIS.Test15.city result = this.fcity;
                // *** Start programmer edit section *** (street.city Get end)

                // *** End programmer edit section *** (street.city Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (street.city Set start)

                // *** End programmer edit section *** (street.city Set start)
                this.fcity = value;
                // *** Start programmer edit section *** (street.city Set end)

                // *** End programmer edit section *** (street.city Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "streetE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View streetE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("streetE", typeof(IIS.Test15.street));
                }
            }
            
            /// <summary>
            /// "streetL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View streetL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("streetL", typeof(IIS.Test15.street));
                }
            }
        }
    }
}
